### ISSUE TITLE
lib/highline.rb not requiring lib/highline/question_asker.rb

### ISSUE THREAD

**Issue by abinoam** [JEG2/highline#165]
Hi @matugm ,

The tests were not able to catch this bug.

I think it would be easily fixed with a 

```ruby
require 'question_asker'
```
on ```lib/highline.rb```

```
NameError: Bad color or uninitialized constant QuestionAsker
	from /Users/abinoam/.rvm/gems/ruby-2.2.3/gems/highline-2.0.0.pre.develop.2/lib/highline/builtin_styles.rb:104:in `const_missing'
	from /Users/abinoam/.rvm/gems/ruby-2.2.3/gems/highline-2.0.0.pre.develop.2/lib/highline.rb:186:in `ask'
	from /Users/abinoam/.rvm/gems/ruby-2.2.3/gems/highline-2.0.0.pre.develop.2/lib/highline/paginator.rb:37:in `continue_paging?'
	from /Users/abinoam/.rvm/gems/ruby-2.2.3/gems/highline-2.0.0.pre.develop.2/lib/highline/paginator.rb:27:in `page_print'
	from /Users/abinoam/.rvm/gems/ruby-2.2.3/gems/highline-2.0.0.pre.develop.2/lib/highline/statement.rb:37:in `format_statement'
	from /Users/abinoam/.rvm/gems/ruby-2.2.3/gems/highline-2.0.0.pre.develop.2/lib/highline/statement.rb:18:in `statement'
	from /Users/abinoam/.rvm/gems/ruby-2.2.3/gems/highline-2.0.0.pre.develop.2/lib/highline/statement.rb:22:in `to_s'
	from /Users/abinoam/.rvm/gems/ruby-2.2.3/gems/highline-2.0.0.pre.develop.2/lib/highline.rb:309:in `render_statement'
	from /Users/abinoam/.rvm/gems/ruby-2.2.3/gems/highline-2.0.0.pre.develop.2/lib/highline.rb:293:in `say'
	from (irb):3
	from /Users/abinoam/.rvm/rubies/ruby-2.2.3/bin/irb:15:in `<main>'
```

**Comment by abinoam** [comment]
The bug shows up in the __acceptance tests__ (with ```rake acceptance```)

**Comment by matugm** [comment]
I will look into it. Can we add a new unit test that covers this problem?
