### ISSUE TITLE
HighLine Terminal::IOConsole#restore_mode does not work with StringIO

### ISSUE THREAD

**Issue by presidentbeef** [JEG2/highline#226]
HighLine version 2.0.0.pre.develop.14

```
2.3.1 :001 > require 'highline'
 => true 
2.3.1 :002 > h = HighLine.new(StringIO.new, StringIO.new)
 => #<HighLine:0x0000000183b188 @input=#<StringIO:0x0000000183b228>, @output=#<StringIO:0x0000000183b1d8>, @multi_indent=true, @indent_size=3, @indent_level=0, @wrap_at=nil, @page_at=nil, @header=nil, @prompt=nil, @key=nil, @use_color=true, @track_eof=true, @terminal=#<HighLine::Terminal::IOConsole:0x0000000183aeb8 @input=#<StringIO:0x0000000183b228>, @output=#<StringIO:0x0000000183b1d8>>> 
2.3.1 :003 > h.page_at = 1
 => 1 
2.3.1 :004 > h.say "\n\n"
NoMethodError: undefined method `echo=' for #<StringIO:0x0000000183b228>
	from /home/justin/.rvm/gems/ruby-2.3.1@engine/gems/highline-2.0.0.pre.develop.14/lib/highline/terminal/io_console.rb:20:in `restore_mode'
	from /home/justin/.rvm/gems/ruby-2.3.1@engine/gems/highline-2.0.0.pre.develop.14/lib/highline/terminal.rb:70:in `ensure in raw_no_echo_mode_exec'
	from /home/justin/.rvm/gems/ruby-2.3.1@engine/gems/highline-2.0.0.pre.develop.14/lib/highline/terminal.rb:70:in `raw_no_echo_mode_exec'
	from /home/justin/.rvm/gems/ruby-2.3.1@engine/gems/highline-2.0.0.pre.develop.14/lib/highline.rb:591:in `get_response_character_mode'
	from /home/justin/.rvm/gems/ruby-2.3.1@engine/gems/highline-2.0.0.pre.develop.14/lib/highline/question.rb:522:in `get_response'
	from /home/justin/.rvm/gems/ruby-2.3.1@engine/gems/highline-2.0.0.pre.develop.14/lib/highline/question.rb:536:in `get_response_or_default'
	from /home/justin/.rvm/gems/ruby-2.3.1@engine/gems/highline-2.0.0.pre.develop.14/lib/highline/question_asker.rb:30:in `ask_once'
	from /home/justin/.rvm/gems/ruby-2.3.1@engine/gems/highline-2.0.0.pre.develop.14/lib/highline.rb:223:in `ask'
	from /home/justin/.rvm/gems/ruby-2.3.1@engine/gems/highline-2.0.0.pre.develop.14/lib/highline/paginator.rb:46:in `continue_paging?'
	from /home/justin/.rvm/gems/ruby-2.3.1@engine/gems/highline-2.0.0.pre.develop.14/lib/highline/paginator.rb:36:in `page_print'
	from /home/justin/.rvm/gems/ruby-2.3.1@engine/gems/highline-2.0.0.pre.develop.14/lib/highline/statement.rb:64:in `format_statement'
	from /home/justin/.rvm/gems/ruby-2.3.1@engine/gems/highline-2.0.0.pre.develop.14/lib/highline/statement.rb:39:in `statement'
	from /home/justin/.rvm/gems/ruby-2.3.1@engine/gems/highline-2.0.0.pre.develop.14/lib/highline/statement.rb:45:in `to_s'
	from /home/justin/.rvm/gems/ruby-2.3.1@engine/gems/highline-2.0.0.pre.develop.14/lib/highline.rb:384:in `render_statement'
	from /home/justin/.rvm/gems/ruby-2.3.1@engine/gems/highline-2.0.0.pre.develop.14/lib/highline.rb:365:in `say'
	from (irb):4
	from /home/justin/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
```

This works prior to 2.0.

**Comment by abinoam** [comment]
Hi @presidentbeef,

You're right! t's not working anymore.
For doing so we're providing a simple compatibility module.
Look at https://github.com/JEG2/highline/blob/master/lib/highline/io_console_compatible.rb
We're using it to make our tests using StringIO pass.
If you have any insight, suggestions of a better way to accomplish it, I would be happy to discuss with it with you.

**Comment by presidentbeef** [comment]
Ah, no that's perfect for me. I only need it for tests as well.

**Comment by abinoam** [comment]
Great 👍 !

I think I should put a note on README to ease the task for others.

And... thanks for reporting it.
